# Generated by Django 5.1.2 on 2024-11-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_department_product_students_employee_detail_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='clearance',
            field=models.TextField(default='High'),
        ),
    ]
