# Generated by Django 5.1.3 on 2024-11-20 00:33

import datetime
import django.views.generic.dates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_on',
            field=models.DateTimeField(default=django.views.generic.dates.timezone_today),
        ),
        migrations.AddField(
            model_name='book',
            name='days_since_created',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
