# Generated by Django 5.1.3 on 2024-11-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_created_on_book_days_since_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='book',
            name='days_since_created',
        ),
    ]
